#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Aug 28 13:26:52 2017

@author: eva
"""

test = [[0.54505451, 0.79257926, 0.90629063, 1.],
        [0.38363836, 0.81938194, 0.90849085, 1.],
        [0.21922192, 0.33003300, 0.75747575, 1.],
        [0.18228177, 0.29717028, 0.54194581, 1.]]

test2 = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
for i in range(4):
    for j in range(4):
        if i == j:
            test2[i][j] = 0
        elif j!=0:
            test2[i][j] = test[i][j]-test[i][j-1]
        else:
            test2[i][j] = test[i][j]
        
for i in test2:
    test = np.array(i)/sum(i)
    print np.cumsum(test)